name: Build and test My Grades App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "Mimito"

  run-ui-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependensies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install 
    - name: Start the application
      run: npm run start &
    - name: Run the UI Tests
      run: npm run test:ui

